import { Simulation } from '../types';

export const simulationDatabase: Simulation[] = [
  // ─── Dữ liệu gốc (High Quality Hand-picked) ───
  {
    id: 1,
    subject: "Vật lý",
    topic: ["phản xạ ánh sáng", "gương phẳng", "định luật phản xạ", "ánh sáng"],
    title: "Bending Light - Phản Xạ & Khúc Xạ",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/bending-light/latest/bending-light_vi.html",
    language: "Tiếng Việt",
    preview: "https://phet.colorado.edu/sims/bending-light/bending-light-600.png",
    guide: "1. Chọn tab 'Phản xạ'\n2. Điều chỉnh góc tới bằng cách kéo đèn laser\n3. Quan sát góc phản xạ bằng thước đo độ",
    grade: ["Lớp 6-7", "Lớp 8-9", "Lớp 10-12"]
  },
  {
    id: 2,
    subject: "Vật lý",
    topic: ["lực đẩy archimedes", "áp lực chất lỏng", "vật chìm nổi", "lực đẩy ácsimét"],
    title: "Buoyancy - Lực Đẩy Archimedes",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/buoyancy/latest/buoyancy_vi.html",
    language: "Tiếng Việt",
    preview: "https://phet.colorado.edu/sims/buoyancy/buoyancy-600.png",
    guide: "1. Kéo thả vật vào bể nước\n2. Quan sát mũi tên lực đẩy và trọng lực\n3. Thay đổi khối lượng riêng của vật và chất lỏng",
    grade: ["Lớp 8-9"]
  },
  {
    id: 3,
    subject: "Toán học",
    topic: ["hàm số bậc hai", "parabol", "đồ thị", "hàm số"],
    title: "Graphing Quadratics - Hàm Bậc Hai",
    platform: "GeoGebra",
    url: "https://www.geogebra.org/material/iframe/id/hZ7hN4D8",
    language: "Đa ngôn ngữ",
    preview: "https://www.geogebra.org/resource/hZ7hN4D8/thumbnail.png",
    guide: "1. Điều chỉnh hệ số a, b, c bằng thanh trượt\n2. Quan sát hình dạng parabol thay đổi\n3. Xác định đỉnh và trục đối xứng",
    grade: ["Lớp 8-9", "Lớp 10-12"]
  },
  {
    id: 4,
    subject: "Hóa học",
    topic: ["cấu tạo nguyên tử", "nguyên tố", "proton", "neutron", "electron"],
    title: "Build an Atom - Xây Dựng Nguyên Tử",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/build-an-atom/latest/build-an-atom_vi.html",
    language: "Tiếng Việt",
    preview: "https://phet.colorado.edu/sims/build-an-atom/build-an-atom-600.png",
    guide: "1. Kéo thả proton, neutron, electron vào tâm\n2. Quan sát tên nguyên tố thay đổi\n3. Kiểm tra tính bền vững của hạt nhân",
    grade: ["Lớp 8-9", "Lớp 10-12"]
  },
  {
    id: 5,
    subject: "Sinh học",
    topic: ["chọn lọc tự nhiên", "tiến hóa", "thỏ", "di truyền"],
    title: "Natural Selection - Chọn Lọc Tự Nhiên",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/natural-selection/latest/natural-selection_vi.html",
    language: "Tiếng Việt",
    preview: "https://phet.colorado.edu/sims/natural-selection/natural-selection-600.png",
    guide: "1. Thêm thỏ vào môi trường\n2. Thêm yếu tố chọn lọc (sói, thức ăn)\n3. Quan sát sự thay đổi số lượng thỏ qua các thế hệ",
    grade: ["Lớp 8-9", "Lớp 10-12"]
  },
  {
    id: 6,
    subject: "Vật lý",
    topic: ["mạch điện", "định luật ohm", "dòng điện", "điện trở"],
    title: "Circuit Construction - Lắp Ráp Mạch Điện DC",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/circuit-construction-kit-dc/latest/circuit-construction-kit-dc_vi.html",
    language: "Tiếng Việt",
    preview: "https://phet.colorado.edu/sims/circuit-construction-kit-dc/circuit-construction-kit-dc-600.png",
    guide: "1. Kéo dây dẫn, pin, bóng đèn ra bảng mạch\n2. Nối chúng lại thành mạch kín\n3. Dùng vôn kế đo hiệu điện thế",
    grade: ["Lớp 8-9", "Lớp 10-12"]
  },
  {
    id: 7,
    subject: "Toán học",
    topic: ["tam giác", "diện tích", "chu vi", "hình học"],
    title: "Area Builder - Xây Dựng Diện Tích",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/area-builder/latest/area-builder_en.html",
    language: "Tiếng Anh (Dễ hiểu)",
    preview: "https://phet.colorado.edu/sims/area-builder/area-builder-600.png",
    guide: "1. Xếp các ô vuông để tạo hình\n2. Quan sát diện tích và chu vi được tính tự động\n3. Thử thách tạo hình có cùng diện tích nhưng chu vi khác nhau",
    grade: ["Lớp 6-7"]
  },
  {
    id: 8,
    subject: "Hóa học",
    topic: ["trạng thái chất", "rắn lỏng khí", "nhiệt độ", "áp suất"],
    title: "States of Matter - Các Trạng Thái Của Chất",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/states-of-matter/latest/states-of-matter_vi.html",
    language: "Tiếng Việt",
    preview: "https://phet.colorado.edu/sims/states-of-matter/states-of-matter-600.png",
    guide: "1. Chọn loại phân tử (Neon, Argon, Oxy, Nước)\n2. Tăng giảm nhiệt độ\n3. Quan sát chuyển động và sự sắp xếp của phân tử",
    grade: ["Lớp 8-9", "Lớp 10-12"]
  },
  {
    id: 9,
    subject: "Vật lý",
    topic: ["dao động", "con lắc lò xo", "đàn hồi"],
    title: "Masses and Springs - Con Lắc Lò Xo",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/masses-and-springs/latest/masses-and-springs_vi.html",
    language: "Tiếng Việt",
    preview: "https://phet.colorado.edu/sims/masses-and-springs/masses-and-springs-600.png",
    guide: "1. Treo quả nặng vào lò xo\n2. Quan sát dao động\n3. Thay đổi độ cứng lò xo và xem chu kỳ thay đổi",
    grade: ["Lớp 10-12"]
  },
  {
    id: 10,
    subject: "Toán học",
    topic: ["xác suất", "thống kê", "tung đồng xu"],
    title: "Probability - Xác Suất Plinko",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/plinko-probability/latest/plinko-probability_en.html",
    language: "Tiếng Anh (Trực quan)",
    preview: "https://phet.colorado.edu/sims/plinko-probability/plinko-probability-600.png",
    guide: "1. Thả bóng rơi qua các chốt\n2. Quan sát phân phối nhị thức hình thành\n3. So sánh kết quả thực tế và lý thuyết",
    grade: ["Lớp 10-12", "Đại học"]
  },
  {
    id: 11,
    subject: "Sinh học",
    topic: ["biểu hiện gen", "protein", "dna", "phiên mã"],
    title: "Gene Expression - Biểu Hiện Gen",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/gene-expression-essentials/latest/gene-expression-essentials_en.html",
    language: "Tiếng Anh",
    preview: "https://phet.colorado.edu/sims/gene-expression-essentials/gene-expression-essentials-600.png",
    guide: "1. Ghép nối các phân tử enzyme và DNA\n2. Quan sát quá trình tạo ra mARN và Protein\n3. Điều chỉnh nồng độ các chất",
    grade: ["Lớp 10-12", "Đại học"]
  },
  {
    id: 12,
    subject: "Vật lý",
    topic: ["lực hấp dẫn", "quỹ đạo", "hành tinh", "mặt trời"],
    title: "Gravity and Orbits - Lực Hấp Dẫn & Quỹ Đạo",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/gravity-and-orbits/latest/gravity-and-orbits_vi.html",
    language: "Tiếng Việt",
    preview: "https://phet.colorado.edu/sims/gravity-and-orbits/gravity-and-orbits-600.png",
    guide: "1. Chọn hệ Mặt Trời - Trái Đất\n2. Bật hiển thị vectơ lực hấp dẫn\n3. Thay đổi khối lượng ngôi sao và xem quỹ đạo thay đổi",
    grade: ["Lớp 10-12"]
  },
  {
    id: 13,
    subject: "Hóa học",
    topic: ["cân bằng phương trình", "phản ứng hóa học"],
    title: "Balancing Chemical Equations - Cân Bằng Phương Trình",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/balancing-chemical-equations/latest/balancing-chemical-equations_vi.html",
    language: "Tiếng Việt",
    preview: "https://phet.colorado.edu/sims/balancing-chemical-equations/balancing-chemical-equations-600.png",
    guide: "1. Chọn một phản ứng (ví dụ: Tạo nước)\n2. Điều chỉnh hệ số trước các chất\n3. Làm cho cân thăng bằng ở cả 2 bên",
    grade: ["Lớp 8-9"]
  },
  {
    id: 14,
    subject: "Toán học",
    topic: ["vectơ", "tổng hợp lực", "toán độ"],
    title: "Vector Addition - Cộng Vectơ",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/vector-addition/latest/vector-addition_vi.html",
    language: "Tiếng Việt",
    preview: "https://phet.colorado.edu/sims/vector-addition/vector-addition-600.png",
    guide: "1. Kéo các vectơ ra mặt phẳng\n2. Xếp nối đuôi nhau để tìm tổng\n3. Xem các thành phần Rx, Ry",
    grade: ["Lớp 10-12"]
  },
  {
    id: 15,
    subject: "Khoa học tự nhiên",
    topic: ["hiệu ứng nhà kính", "khí hậu", "trái đất"],
    title: "Greenhouse Effect - Hiệu Ứng Nhà Kính",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/greenhouse-effect/latest/greenhouse-effect_en.html",
    language: "Tiếng Anh",
    preview: "https://phet.colorado.edu/sims/greenhouse-effect/greenhouse-effect-600.png",
    guide: "1. Thêm các lớp mây hoặc khí nhà kính\n2. Quan sát nhiệt độ bề mặt Trái Đất tăng lên\n3. Xem sự phản xạ của tia hồng ngoại",
    grade: ["Lớp 6-7", "Lớp 8-9"]
  },

  // ─── Dữ liệu bổ sung (Extended Database) ───

  // Vật Lý
  {
    id: 16,
    subject: "Vật lý",
    topic: ["lò xo", "hooke", "đàn hồi", "lực", "cơ học", "biến dạng"],
    title: "Hooke's Law - Định Luật Hooke",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/hookes-law/latest/hookes-law_vi.html",
    language: "Tiếng Việt",
    preview: "https://phet.colorado.edu/sims/hookes-law/hookes-law-600.png",
    guide: "1. Kéo hoặc nén lò xo bằng chuột\n2. Quan sát vectơ lực đàn hồi thay đổi\n3. Thay đổi độ cứng của lò xo",
    grade: ["Lớp 10-12"]
  },
  {
    id: 17,
    subject: "Vật lý",
    topic: ["ném xiên", "ném ngang", "parabol", "chuyển động", "quỹ đạo"],
    title: "Projectile Motion - Chuyển Động Ném Xiên",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/projectile-motion/latest/projectile-motion_vi.html",
    language: "Tiếng Việt",
    preview: "https://phet.colorado.edu/sims/projectile-motion/projectile-motion-600.png",
    guide: "1. Điều chỉnh góc bắn và vận tốc ban đầu của pháo\n2. Bắn vật thể và quan sát quỹ đạo\n3. Thêm lực cản không khí để xem sự khác biệt",
    grade: ["Lớp 10-12"]
  },
  {
    id: 18,
    subject: "Vật lý",
    topic: ["điện trường", "điện tích", "vectơ", "coulomb", "lực điện"],
    title: "Charges and Fields - Điện Tích và Điện Trường",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/charges-and-fields/latest/charges-and-fields_vi.html",
    language: "Tiếng Việt",
    preview: "https://phet.colorado.edu/sims/charges-and-fields/charges-and-fields-600.png",
    guide: "1. Kéo các điện tích dương/âm ra màn hình\n2. Quan sát hướng các đường sức điện\n3. Dùng cảm biến để đo cường độ điện trường",
    grade: ["Lớp 10-12"]
  },
  {
    id: 19,
    subject: "Vật lý",
    topic: ["con lắc", "dao động", "chu kỳ", "tần số", "năng lượng"],
    title: "Pendulum Lab - Dao Động Con Lắc",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/pendulum-lab/latest/pendulum-lab_vi.html",
    language: "Tiếng Việt",
    preview: "https://phet.colorado.edu/sims/pendulum-lab/pendulum-lab-600.png",
    guide: "1. Kéo con lắc lệch khỏi vị trí cân bằng rồi thả\n2. Đo chu kỳ dao động\n3. Thay đổi chiều dài dây treo và quan sát",
    grade: ["Lớp 10-12"]
  },
  {
    id: 20,
    subject: "Vật lý",
    topic: ["năng lượng", "động năng", "thế năng", "bảo toàn", "ma sát"],
    title: "Energy Skate Park - Năng Lượng Trong Sân Trượt",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/energy-skate-park/latest/energy-skate-park_vi.html",
    language: "Tiếng Việt",
    preview: "https://phet.colorado.edu/sims/energy-skate-park/energy-skate-park-600.png",
    guide: "1. Thiết kế đường trượt cho vận động viên\n2. Quan sát biểu đồ chuyển hóa Động năng - Thế năng\n3. Bật ma sát để thấy sự hao hụt năng lượng",
    grade: ["Lớp 8-9", "Lớp 10-12"]
  },
  {
    id: 21,
    subject: "Vật lý",
    topic: ["sóng", "dao động", "tần số", "biên độ", "bước sóng"],
    title: "Wave on a String - Sóng Trên Dây",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/wave-on-a-string/latest/wave-on-a-string_vi.html",
    language: "Tiếng Việt",
    preview: "https://phet.colorado.edu/sims/wave-on-a-string/wave-on-a-string-600.png",
    guide: "1. Tạo xung sóng hoặc dao động liên tục\n2. Thay đổi biên độ và tần số nguồn sóng\n3. Quan sát sự phản xạ tại đầu dây cố định/tự do",
    grade: ["Lớp 10-12"]
  },
  {
    id: 22,
    subject: "Vật lý",
    topic: ["lực", "ma sát", "newton", "gia tốc", "chuyển động"],
    title: "Forces and Motion - Lực và Chuyển Động",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/forces-and-motion-basics/latest/forces-and-motion-basics_vi.html",
    language: "Tiếng Việt",
    preview: "https://phet.colorado.edu/sims/forces-and-motion-basics/forces-and-motion-basics-600.png",
    guide: "1. Tác dụng lực đẩy lên vật\n2. Quan sát sự thay đổi vận tốc và gia tốc\n3. Thử nghiệm trên mặt sàn có ma sát và không ma sát",
    grade: ["Lớp 8-9", "Lớp 10-12"]
  },
  {
    id: 23,
    subject: "Vật lý",
    topic: ["vật lý", "mô phỏng", "2D", "tự tạo", "thí nghiệm", "cơ học"],
    title: "Algodoo - Mô phỏng Vật lý 2D",
    platform: "Algodoo",
    url: "http://www.algodoo.com/",
    language: "Tiếng Anh",
    preview: "https://via.placeholder.com/600x400/2563eb/ffffff?text=Algodoo+Physics",
    guide: "1. Tải phần mềm hoặc dùng bản web (nếu có)\n2. Vẽ các vật thể 2D và gắn động cơ, lò xo\n3. Nhấn Play để xem mô phỏng vật lý",
    grade: ["Lớp 8-9", "Lớp 10-12"]
  },

  // Hóa Học
  {
    id: 24,
    subject: "Hóa học",
    topic: ["nồng độ", "dung dịch", "mol", "pha chế", "molarity"],
    title: "Concentration - Nồng Độ Dung Dịch",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/concentration/latest/concentration_vi.html",
    language: "Tiếng Việt",
    preview: "https://phet.colorado.edu/sims/concentration/concentration-600.png",
    guide: "1. Thêm chất tan vào dung môi\n2. Quan sát sự thay đổi nồng độ mol\n3. Làm bay hơi dung môi để thấy bão hòa",
    grade: ["Lớp 8-9", "Lớp 10-12"]
  },
  {
    id: 25,
    subject: "Hóa học",
    topic: ["pH", "axit", "bazơ", "nước", "ion H+", "OH-"],
    title: "pH Scale - Thang pH Axit & Bazơ",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/ph-scale/latest/ph-scale_vi.html",
    language: "Tiếng Việt",
    preview: "https://phet.colorado.edu/sims/ph-scale/ph-scale-600.png",
    guide: "1. Chọn dung dịch (nước, xà phòng, axit pin...)\n2. Nhúng đầu dò pH để đo giá trị\n3. Pha loãng với nước và quan sát sự thay đổi pH",
    grade: ["Lớp 8-9", "Lớp 10-12"]
  },
  {
    id: 26,
    subject: "Hóa học",
    topic: ["phản ứng", "sản phẩm", "chất dư", "mol", "tỉ lệ"],
    title: "Reactants, Products and Leftovers",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/reactants-products-and-leftovers/latest/reactants-products-and-leftovers_vi.html",
    language: "Tiếng Việt",
    preview: "https://phet.colorado.edu/sims/reactants-products-and-leftovers/reactants-products-and-leftovers-600.png",
    guide: "1. Chọn phản ứng làm bánh mì hoặc phản ứng hóa học\n2. Thay đổi số lượng nguyên liệu đầu vào\n3. Xác định chất hết (chất hạn chế) và chất dư",
    grade: ["Lớp 8-9", "Lớp 10-12"]
  },
  {
    id: 27,
    subject: "Hóa học",
    topic: ["khí", "áp suất", "thể tích", "nhiệt độ", "PV=nRT"],
    title: "Gas Properties - Định Luật Khí Lý Tưởng",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/gas-properties/latest/gas-properties_vi.html",
    language: "Tiếng Việt",
    preview: "https://phet.colorado.edu/sims/gas-properties/gas-properties-600.png",
    guide: "1. Bơm khí vào buồng chứa\n2. Thay đổi thể tích hoặc nhiệt độ\n3. Quan sát sự thay đổi áp suất theo định luật",
    grade: ["Lớp 10-12"]
  },
  {
    id: 28,
    subject: "Hóa học",
    topic: ["cực tính", "liên kết", "điện tích", "phân tử", "hình dạng"],
    title: "Molecule Polarity - Phân Tử và Cực Tính",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/molecule-polarity/latest/molecule-polarity_vi.html",
    language: "Tiếng Việt",
    preview: "https://phet.colorado.edu/sims/molecule-polarity/molecule-polarity-600.png",
    guide: "1. Thay đổi độ âm điện của các nguyên tử\n2. Bật hiển thị vectơ lưỡng cực\n3. Quan sát sự phân bố điện tích",
    grade: ["Lớp 10-12"]
  },
  {
    id: 29,
    subject: "Hóa học",
    topic: ["chuẩn độ", "axit", "bazơ", "thí nghiệm", "lab ảo"],
    title: "Virtual Lab - Chuẩn Độ (Titration)",
    platform: "ChemCollective",
    url: "https://chemcollective.org/vlabs",
    language: "Tiếng Anh",
    preview: "https://via.placeholder.com/600x400/10b981/ffffff?text=Titration+Lab",
    guide: "1. Chọn hóa chất từ kho (axit, bazơ, chỉ thị)\n2. Thực hiện thao tác nhỏ giọt chuẩn độ\n3. Quan sát điểm chuyển màu",
    grade: ["Lớp 10-12", "Đại học"]
  },
  {
    id: 30,
    subject: "Hóa học",
    topic: ["dung dịch", "pha chế", "nồng độ", "mol", "thí nghiệm"],
    title: "Virtual Lab - Pha Chế Dung Dịch",
    platform: "ChemCollective",
    url: "https://chemcollective.org/vlabs/solution-making",
    language: "Tiếng Anh",
    preview: "https://via.placeholder.com/600x400/10b981/ffffff?text=Solution+Making",
    guide: "1. Tính toán lượng chất tan cần thiết\n2. Sử dụng cân và bình định mức ảo\n3. Pha chế dung dịch nồng độ chính xác",
    grade: ["Lớp 10-12"]
  },

  // Sinh Học
  {
    id: 33,
    subject: "Sinh học",
    topic: ["màng", "tế bào", "kênh", "vận chuyển", "thẩm thấu", "ion"],
    title: "Membrane Channels - Màng Tế Bào",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/membrane-channels/latest/membrane-channels_en.html",
    language: "Tiếng Anh",
    preview: "https://phet.colorado.edu/sims/membrane-channels/membrane-channels-600.png",
    guide: "1. Thêm các kênh ion vào màng tế bào\n2. Quan sát sự di chuyển của các hạt qua màng\n3. Tìm hiểu về vận chuyển thụ động",
    grade: ["Lớp 10-12"]
  },
  {
    id: 34,
    subject: "Sinh học",
    topic: ["nơ-ron", "thần kinh", "xung điện", "synapse", "não"],
    title: "Neuron - Hoạt Động Của Nơ-ron",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/neuron/latest/neuron_en.html",
    language: "Tiếng Anh",
    preview: "https://phet.colorado.edu/sims/neuron/neuron-600.png",
    guide: "1. Kích thích nơ-ron để tạo xung thần kinh\n2. Quan sát sự di chuyển của ion Na+ và K+\n3. Xem biểu đồ điện thế màng",
    grade: ["Lớp 10-12", "Đại học"]
  },
  {
    id: 35,
    subject: "Sinh học",
    topic: ["DNA", "điện di", "gel", "phân tử", "di truyền", "PCR"],
    title: "DNA Electrophoresis - Điện Di DNA",
    platform: "BioInteractive",
    url: "https://www.biointeractive.org/classroom-resources/dna-virtual-lab",
    language: "Tiếng Anh",
    preview: "https://via.placeholder.com/600x400/16a34a/ffffff?text=DNA+Electrophoresis",
    guide: "1. Chuẩn bị mẫu DNA và gel agarose\n2. Chạy điện di và nhuộm gel\n3. Phân tích các băng DNA dưới tia UV",
    grade: ["Lớp 10-12", "Đại học"]
  },

  // Toán Học
  {
    id: 41,
    subject: "Toán học",
    topic: ["hình học", "tam giác", "đường tròn", "vẽ hình", "chứng minh"],
    title: "GeoGebra Geometry - Hình Học Phẳng",
    platform: "GeoGebra",
    url: "https://www.geogebra.org/geometry?lang=vi",
    language: "Tiếng Việt",
    preview: "https://via.placeholder.com/600x400/6366f1/ffffff?text=GeoGebra+Geometry",
    guide: "1. Dùng công cụ để vẽ điểm, đường thẳng, đường tròn\n2. Đo góc và độ dài đoạn thẳng\n3. Quan sát các tính chất hình học khi di chuyển điểm",
    grade: ["Lớp 6-7", "Lớp 8-9"]
  },
  {
    id: 42,
    subject: "Toán học",
    topic: ["đồ thị", "hàm số", "parabol", "bậc 2", "sin", "cos"],
    title: "GeoGebra Graphing - Vẽ Đồ Thị",
    platform: "GeoGebra",
    url: "https://www.geogebra.org/graphing?lang=vi",
    language: "Tiếng Việt",
    preview: "https://via.placeholder.com/600x400/6366f1/ffffff?text=GeoGebra+Graphing",
    guide: "1. Nhập phương trình hàm số (ví dụ: y = x^2)\n2. Quan sát đồ thị được vẽ ngay lập tức\n3. Tìm giao điểm, cực trị",
    grade: ["Lớp 8-9", "Lớp 10-12"]
  },
  {
    id: 46,
    subject: "Toán học",
    topic: ["đồ thị", "hàm số", "parabol", "sin", "cos", "slider"],
    title: "Desmos Graphing Calculator",
    platform: "Desmos",
    url: "https://www.desmos.com/calculator?lang=vi",
    language: "Tiếng Việt",
    preview: "https://via.placeholder.com/600x400/22c55e/ffffff?text=Desmos+Calculator",
    guide: "1. Nhập hàm số bất kỳ\n2. Thêm thanh trượt (slider) cho các tham số\n3. Xem đồ thị biến đổi động khi kéo thanh trượt",
    grade: ["Lớp 8-9", "Lớp 10-12"]
  },
  {
    id: 49,
    subject: "Toán học",
    topic: ["phân số", "số học", "chia", "rút gọn"],
    title: "Fractions Intro - Làm Quen Phân Số",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/fractions-intro/latest/fractions-intro_vi.html",
    language: "Tiếng Việt",
    preview: "https://phet.colorado.edu/sims/fractions-intro/fractions-intro-600.png",
    guide: "1. Chọn hình dạng (bánh tròn, thanh chữ nhật)\n2. Chia nhỏ và tô màu để biểu diễn phân số\n3. So sánh các phân số với nhau",
    grade: ["Lớp 6-7"]
  },
  {
    id: 50,
    subject: "Toán học",
    topic: ["tích phân", "đạo hàm", "giải tích", "diện tích", "đường cong"],
    title: "Calculus Grapher - Đồ Thị Giải Tích",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/calculus-grapher/latest/calculus-grapher_en.html",
    language: "Tiếng Anh",
    preview: "https://phet.colorado.edu/sims/calculus-grapher/calculus-grapher-600.png",
    guide: "1. Vẽ đồ thị hàm số f(x)\n2. Quan sát đồ thị đạo hàm f'(x) và nguyên hàm F(x) được tạo ra tự động\n3. Thay đổi hình dạng hàm gốc để xem mối liên hệ",
    grade: ["Lớp 10-12", "Đại học"]
  },
  {
    id: 51,
    subject: "Toán học",
    topic: ["đường thẳng", "phương trình", "hệ số góc", "y = ax + b"],
    title: "Graphing Lines - Đồ Thị Đường Thẳng",
    platform: "PhET",
    url: "https://phet.colorado.edu/sims/html/graphing-lines/latest/graphing-lines_en.html",
    language: "Tiếng Anh",
    preview: "https://phet.colorado.edu/sims/graphing-lines/graphing-lines-600.png",
    guide: "1. Điều chỉnh hệ số góc (slope) và tung độ gốc (y-intercept)\n2. Quan sát đường thẳng thay đổi trên mặt phẳng tọa độ\n3. Thử thách tìm phương trình từ đường thẳng cho trước",
    grade: ["Lớp 8-9"]
  },
  {
    id: 52,
    subject: "Toán học",
    topic: ["công cụ", "vẽ hình", "tương tác", "algebra tiles", "đa giác"],
    title: "Polypad - Bảng Tương Tác Toán Học",
    platform: "Mathigon",
    url: "https://mathigon.org/polypad",
    language: "Tiếng Anh",
    preview: "https://via.placeholder.com/600x400/f43f5e/ffffff?text=Mathigon+Polypad",
    guide: "1. Kéo thả các hình khối, phân số, hoặc đại số từ thanh công cụ\n2. Sắp xếp, xoay, và ghép nối chúng\n3. Dùng để dạy hình học, số học trực quan",
    grade: ["Lớp 6-7", "Lớp 8-9"]
  },
  {
    id: 54,
    subject: "Toán học",
    topic: ["đại số", "phương trình", "bất phương trình", "hệ phương trình"],
    title: "Khan Academy - Đại Số (Algebra)",
    platform: "Khan Academy",
    url: "https://vi.khanacademy.org/math/algebra",
    language: "Tiếng Việt",
    preview: "https://via.placeholder.com/600x400/14b8a6/ffffff?text=Khan+Academy+Algebra",
    guide: "1. Chọn chủ đề đại số cần ôn tập\n2. Xem video bài giảng và làm bài tập tương tác\n3. Theo dõi tiến độ học tập",
    grade: ["Lớp 8-9", "Lớp 10-12"]
  },
  {
    id: 57,
    subject: "Toán học",
    topic: ["giải phương trình", "đạo hàm", "tích phân", "ma trận", "calculator"],
    title: "Wolfram Alpha - Siêu Máy Tính",
    platform: "Wolfram",
    url: "https://www.wolframalpha.com/",
    language: "Tiếng Anh",
    preview: "https://via.placeholder.com/600x400/dd6b20/ffffff?text=Wolfram+Alpha",
    guide: "1. Nhập bất kỳ bài toán nào (bằng tiếng Anh)\n2. Nhận kết quả giải chi tiết từng bước\n3. Xem đồ thị và các thông tin liên quan",
    grade: ["Lớp 10-12", "Đại học"]
  }
];